### ISSUE TITLE
Fix invoke restmethod handling.  Don't assume it's going to work.

### ISSUE THREAD

**Issue by MWJ1m** [singlekorn/Update-PanTag#2]
Any  Invoke-RestMethod should be at least wrapped to get a 200 response or log an error.  

I took a VERY lazy approach to this when dealing with slack, but this will probably give you a sense.  I defined every call / response in a script that I called to kinda flatten it all.  Then I only did the thing if the api call 'worked'

## function definition.  debatable should handle http response coding...or have a function that calls a function, and... oh no I've gone cross eyed.

Function SlackAPI-InviteUserPrivateChannel
{
    Param
    (
        [string]$slackChannelId,
        [string]$UserID
    )

    $token = SlackAPI-GetToken
    $uri = 'https://slack.com/api/conversations.invite'
    $body = @{
        token = $token
        channel = $slackChannelId
        users = $UserID
    }

    $response = Invoke-RestMethod -uri $uri -Body $body #-ContentType 'application/x-www-form-urlencoded'
    return $response
}

## Lazy man's slack call that does ok instead of Http 200.  Same dif.  slack specific stuff added for context, but irrelevant. 

# Add To Slack
    foreach ($user in $AddToSlackChannel)
    {
        if($user.ADUserID) #ignore blank array
        {

            $UserID = $user.ADUserID
            $response3 = SlackAPI-InviteUserPrivateChannel -slackChannelId $slackChannelId -UserID $UserID
        
            if ($response3.ok -eq "True")
            {
            $log = "$UserID added to $slackChannelId"
            #Write-Host "$UserID added to $slackChannelId"
            $Context.LogMessage($log, "Information")
            }
            else
            {
        
            $log = "Failed to add $UserID to $slackChannelId. $response3".tostring()
            #Write-Host "$log"
            $Context.LogMessage($log, "Error")
            }
        }
    }

**Comment by singlekorn** [comment]
Addressed in #3.  This script uses two PAN-OS API endpoints: one being REST and the other is their legacy XML interface, which is the only one that supports the PAN-OS Commit function.

Added the appropriate error checking for success API requests for both endpoint types.

**Comment by MWJ1m** [comment]
Looks awesome man
